config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :entries,          only: [:show, :edit, :update, :create, :destroy]
  resources :comments,     only: [:create, :edit, :update, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry
  belongs_to :user
  validates :user_id, presence: true
  validates :entry_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: [:destroy, :edit]
  
  def create
    @entry = Entry.find_by(id: params[:comment][:entry_id])
    @comment = @entry.comments.build(entry_params)
    if @comment.save
      flash[:success] = "Commented"
    else
  	  flash[:danger] = "You must type comment text!"
    end
      redirect_to @entry
  end

  def index
    redirect_to root_url
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
  end

  def update
  	@comment = Comment.find_by(id: params[:id])
  	@comment.content = params[:comment][:content]
    if @comment.save
      flash[:success] = "Edited"
      redirect_to @entry
    else
  	  @feed_items = []
  	  render 'static_pages/home'
    end
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    flash[:success] = "comment deleted"
    redirect_to root_url
  end

  private

    def entry_params
      params.require(:comment).permit(:content, :user_id)
    end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
  <span class="content truncate">
    <%= comment.content %>
  </span>
  <span class="timestamp">
    Posted by <span class="user"><%= link_to comment.user.name, comment.user %></span> about <%= time_ago_in_words(comment.created_at) %> ago.
    <% if current_user?(comment.user) %>
      <%= link_to "Edit", edit_comment_path(comment.id) %>
      <%= link_to "Delete", comment, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/comments/edit.html.erb
<%= render 'shared/comment_form', object: @comment.entry %>